import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import path from "path";

export default defineConfig({
  plugins: [react()],
  test: {
    environment: "happy-dom",
    globals: true,
    setupFiles: ["./src/__tests__/setup.ts"],
    include: ["src/**/*.test.{ts,tsx}"],
    css: false,
    coverage: {
      provider: "v8",
      reporter: ["text", "text-summary", "lcov", "html"],
      reportsDirectory: "./coverage",
      include: [
        "src/**/*.{ts,tsx}",
      ],
      exclude: [
        "src/**/*.test.{ts,tsx}",
        "src/**/*.styles.ts",
        "src/**/*.d.ts",
        "src/__tests__/**",
        "src/app/**/page.tsx",
        "src/app/layout.tsx",
        "src/app/error.tsx",
        "src/app/global-error.tsx",
        "src/app/loading.tsx",
        "src/app/not-found.tsx",
        "src/app/providers/**",
        "src/shared/styles/**",
        "src/shared/config/**",
        "src/shared/ui/Skeleton.tsx",
        "src/shared/api/supabase.ts",
        "src/shared/api/db.ts",
        "src/features/landing/**",
        "src/features/setup-wizard/ui/SetupWizard.tsx",
        "src/features/setup-wizard/ui/steps/**",
        "src/features/analyze-game/model/useAnalysis.ts",
        "src/features/analyze-game/ui/AnalyzePage.tsx",
        "src/features/analyze-game/ui/HistoryPage.hooks.ts",
        "src/features/analyze-game/ui/HistoryPage.utils.ts",
        "src/features/analyze-game/ui/HistoryPage.tsx",
        "src/features/analyze-game/ui/ResultCard.tsx",
        "src/features/analyze-game/ui/history/**",
        "src/features/analyze-game/ui/result/**",
        "src/features/manage-library/ui/GameLibrary.tsx",
        "src/features/manage-library/ui/GameLibrary.hooks.ts",
        "src/features/manage-library/ui/GameRow.tsx",
        "src/features/manage-library/ui/GameTable.tsx",
        "src/features/manage-library/ui/LibraryPagination.tsx",
        "src/features/manage-library/ui/EpicImport.tsx",
        "src/features/manage-library/ui/SteamImport.tsx",
        "src/features/manage-library/ui/FileImport.tsx",
        "src/features/manage-library/ui/PasteImport.tsx",
        "src/features/manage-library/ui/ScoreCalcModal.tsx",
        "src/features/manage-library/ui/LibraryStats.tsx",
        "src/features/manage-library/ui/LibraryToolbar.tsx",
        "src/features/manage-library/ui/ImportSection.tsx",
        "src/features/manage-settings/ui/SettingsPage.tsx",
        "src/features/manage-settings/ui/AccountSection.tsx",
        "src/features/manage-settings/ui/ProviderSection.tsx",
        "src/features/manage-settings/ui/TasteSection.tsx",
        "src/features/help-guide/**",
        "src/features/updater/ui/UpdateNotification.tsx",
        "src/features/auth/lib/epic.ts",
        "src/features/auth/lib/steam.ts",
        "src/features/manage-library/ui/GameLibrary.utils.ts",
        "src/widgets/app-shell/ui/AppShell.tsx",
        "src/widgets/app-shell/ui/AppShellSkeleton.tsx",
        "src/widgets/app-shell/ui/KeepAlivePages.tsx",
      ],
      thresholds: {
        lines: 85,
        functions: 85,
        branches: 80,
        statements: 85,
      },
    },
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
});
